before:
  hooks:
  - go mod tidy
  
project_name: jetdocsctl

builds:
  - ldflags: "-extldflags= -w -X 'github.com/hooksie1/jetdocs/cmd.Version={{.Tag}}-{{.ShortCommit}}'"
    env:
      - "CGO_ENABLED=0"
      - "GO111MODULE=on"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
source:
  enabled: true